---
title: "Resaerch Journey"
---


<br>

## Publications

- **David S. Bullock, Taro Mieno, and Jaeseok Hwang (2020)**  <br> The value of conducting on-farm field trials using precision agriculture technology: <br> a theory and simulations. *Precision Agriculture*, 21, 1027-1044.

    <span style="font-size: 85%;">[<i class="fas fa-book"></i> Link to the published paper](https://link.springer.com/article/10.1007/s11119-019-09706-1)</span>


## Work in Progress

- **Leveraging Multi-Field On-Farm Experiment Data: Evaluating Economic Gains and Externalities in Precision Agriculture** <br>
   (with D. Bullock and T. Mieno)  
   <span style="font-size: 75%;">[<i class="fab fa-github"></i> GitHub Repository](<https://github.com/jaeseokh/value_multifield_ofpe>)</span>  
   <span style="font-size: 75%;">[<i class="fas fa-file-pdf"></i> PDF File](<PDF_File_Link_1>)</span>

- **Evaluating the Profitability of Corn Seeding Decisions: <br> Insights from On-Farm Precision Experiments Data** <br>
  (with D. Bullock and T. Mieno)  
   <span style="font-size: 75%;">[<i class="fab fa-github"></i> GitHub Repository](<https://github.com/jaeseokh/corn_seed_response>)</span>  
   <span style="font-size: 75%;">[<i class="fas fa-file-pdf"></i> PDF File](<PDF_File_Link_2>)</span>

- **Do the shape of yield distribution vary by nitrogen rate and climate conditions?: <br> cross validate the estimated distribution with higher moment-based approaches** <br> 
 (with D. Bullock and T. Mieno)  
   <span style="font-size: 75%;">[<i class="fab fa-github"></i> GitHub Repository](<https://github.com/jaeseokh/yield_distribution>)</span>  
   <span style="font-size: 75%;">[<i class="fas fa-file-pdf"></i> PDF File](<PDF_File_Link_3>)</span>

- **Informing Site-Specific Input Management for Maize in KwaZulu Natal, South Africa:<br> Using On-farm Experimentation and Statistical Techniques** <br> 
  (with M. Delport, D. Bullock, and T.Mieno)   
   - I served as the primary driver for data handling, managed version control for the analytical software (using R), <br> and developed robust data processing workflows.
 