---
format: 
  pdf: 
    documentclass: article
    geometry:
      - top=12mm
      - left=15mm
      - right=15mm
      - bottom=8mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '11pt'
    include-in-header: 
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \usepackage{wrapfig}
        \usepackage{enumitem}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}
        \setlength{\columnsep}{3em}
        \setlist[itemize]{nosep, left=0pt}
---

\begin{huge}\begin{center}{\bf JAESEOK HWANG}\end{center}\end{huge}

\begin{center}\href{mailto:jaeseok2@illinois.edu}{jaeseok2@illinois.edu} ∙ 217-778-8776 ∙ \href{https://github.com/jaeseokh}{Github} ∙ \href{https://www.linkedin.com/in/jaeseok-hwang-0b06741a1}{LinkedIn}\end{center}

\vspace{2pt}
\begin{center}
\parbox{0.9\textwidth}{
Ph.D. Candidate in Quantitative Economics with 5+ years of experience building ETL pipelines. Expertise in Machine Learning to solve optimization problems using geospatial and time-series data.
}
\end{center}
\vspace{2pt}

\begin{large}{\bf PROFESSIONAL EXPERIENCE (Research Assistant)} \vspace{1pt} \hrule \end{large}

\begin{multicols}{2}
  \begin{flushleft}{\bf Data Intensive Farm Management (USDA NRCS)}\end{flushleft}
  \begin{flushright}Sep 2020 – Aug 2025 \end{flushright}
\end{multicols}
\vspace{-4pt}
\begin{itemize}[left=1.5mm, itemsep=1pt, topsep=0pt]
  \item \textbf{Engineered} Python/R data pipelines to process and integrate 500k+ geospatial and time-series records, enabling large-scale modeling and public data delivery.
  \item \textbf{Collaborated with} Oracle cloud engineers to support scalable ETL workflows, developing core R/Python scripts for processing of 300+ unique datasets.
  \item \textbf{Developed and benchmarked} tree-based models (XGBoost, Causal Forest) to forecast performance outcomes and improve accuracy over baseline methods.
\end{itemize}
\vspace{-2pt}

\begin{multicols}{2}
  \begin{flushleft}{\bf Center for the Economics of Sustainability (UIUC)}\end{flushleft}
  \begin{flushright}Jan 2021 – Aug 2024 \end{flushright}
\end{multicols}
\vspace{-4pt}
\begin{itemize}[left=1.5mm, itemsep=1pt, topsep=0pt]
  \item \textbf{Conducted} large-scale economic and geospatial scenario analyses using Monte Carlo simulations to evaluate the profitability and sustainability of different business strategies.
  \item \textbf{Applied} panel-based counterfactual models to estimate the economic impact of management changes, informing national-scale policy studies.
\end{itemize}
\vspace{-2pt}


\begin{large}{\bf DATA SCIENCE AND ECONOMICS PROJECTS}
  \vspace{1pt}
  \hrule
\end{large}
\vspace{1pt}
\textit{Reproducible Code Portfolio: \href{https://github.com/jaeseokh}{github.com/jaeseokh}}
\vspace{4pt}

\textbf{Predictive Model Generalization and Validation}
\vspace{-4pt}
\begin{itemize}[left=1.5mm, itemsep=1pt, topsep=0pt]
  \item Built and validated ML models (XGBoost, Causal Forest, PyTorch MLP) to develop a framework for assessing out-of-sample performance across 100+ distinct environments.
\end{itemize}
\vspace{-2pt}

\textbf{Causal Inference for Optimal Resource Allocation}
\vspace{-4pt}
\begin{itemize}[left=1.5mm, itemsep=1pt, topsep=0pt]
  \item Applied Generalized Additive Models (GAMs) to estimate the causal effect of input levels on productivity, uncovering systematic inefficiencies in resource allocation.
\end{itemize}
\vspace{-2pt}

\textbf{Full Distributional Modeling for Risk Analysis}
\vspace{-4pt}
\begin{itemize}[left=1.5mm, itemsep=1pt, topsep=0pt]
  \item Designed a novel framework using Quantile Forests and Maximum Entropy methods to model full outcome distributions, enabling a more complete assessment of risk.
\end{itemize}
\vspace{-2pt}

\textbf{Geospatial Economic Analysis for Site-Specific Investment}
\vspace{-4pt}
\begin{itemize}[left=1.5mm, itemsep=1pt, topsep=0pt]
  \item Led spatial and economic analysis to develop a targeted resource allocation strategy for a national-scale initiative in partnership with South Africa's BFAP.
\end{itemize}
\vspace{1pt}


\begin{large}{\bf EDUCATION}
  \vspace{2pt}
  \hrule
\end{large}

\begin{multicols}{2}
  \begin{flushleft}{\bf University of Illinois at Urbana-Champaign} \\
  \hspace{5 mm}Ph.D. Agricultural and Applied Economics \end{flushleft}
  \begin{flushright}Expected Dec. 2025\end{flushright}
\end{multicols}
\vspace{-4pt}

\begin{multicols}{2}
  \begin{flushleft}{\bf University of Illinois Urbana-Champaign} \\
  \hspace{5 mm}M.A. Agricultural and Applied Economics \end{flushleft}
  \begin{flushright}May 2020\end{flushright}
\end{multicols}
\vspace{-4pt}

\begin{multicols}{2}
  \begin{flushleft}{\bf Sogang University} \\
  \hspace{5 mm}B.S. Economics \end{flushleft}
  \begin{flushright}Aug. 2013, South Korea\end{flushright}
\end{multicols}
\vspace{1pt}

\begin{large}{\bf TECHNICAL SKILLS}
  \vspace{2pt}
  \hrule
\end{large}

\vspace{2pt}
\textbf{Languages:} R (Expert), Python (Proficient), SQL \hspace{2em} \textbf{Tools:} GitHub, Jupyter, QGIS, Quarto
\vspace{2pt}

\textbf{Data Science \& ML:} Scikit-learn, PyTorch, Pandas.
\vspace{2pt}

\textbf{Methods:} Causal Inference, Bayesian Models, Time-Series Analysis, Geospatial Analysis